kind: Service
apiVersion: v1
metadata:
  name: pants
spec:
  selector:
    app: pants
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
----
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: pants-deployment
  labels:
    app: pants
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pants
  template:
    metadata:
      labels:
        app: pants
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
